apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskapp
spec:
  rules:
  - host: taskapp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: taskapp
            port:
              number: 80